language: rust
rust:
    - stable
cache: cargo
os:
    - linux

script:
    - cargo test --no-default-features --features x64_128
    - cargo test --no-default-features --features x128_128
    - cargo test --no-default-features --features x128_256
